# This file is generated by `. project-config`. Any changes made here are overwritten.

PROJECT = pagoda

install:
	pip3 install -e .

edit:
	make format && make lint && make typecheck && make badge

format:
	black $(PROJECT)

typecheck:
	mypy --show-error-codes --disable-error-code attr-defined $(PROJECT)

badge:
	python3 utils/create_badge.py -c 'make lint'

lint:
	pylint -d fixme $(PROJECT)

todo:
	python3 utils/list_todos.py "`grep -rnw . -e '# TODO'`"
